#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

#библиотека позволяет прогонять линтером только те файлы, которые были изменены
# в package.json параметр lint-staged
npx lint-staged

#npm run build:prod
#npm run lint:ts
#npm run lint:scss
#npm run test:unit
#npm run storybook:build
#npm run test:ui
